apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: web
