# Default values for myhelmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.14.1"

service:
  type: NodePort
  port: 80
  nodePort: 30080

nodeName: worker01
