apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: JSON_APP1
      valueFrom:
        configMapKeyRef:
          name: last-cm
          key: plik1
    envFrom:
      - configMapRef:
          name: from-env-cm
