apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: load-generator
  name: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - while sleep 0.01; do wget -q -O- http://php-apache; done
        image: busybox:1.28
        name: c1

