apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    some: label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      name: web-pod
      labels:
        app: web-app
    spec:
      containers:
        - name: c1
          image: nginx

